"""
Agent 3 - Insights Agent (narrative layer only).

All statistics are computed deterministically in pipeline/eda.py. This agent is
fed ONLY the computed numbers and writes a short plain-English narrative. It is
explicitly instructed never to invent or compute a statistic itself.
Stateless call via agents/base.py.
"""

from __future__ import annotations

import json

import config
from agents import base
from pipeline.eda import EDAResult

SYSTEM_PROMPT = """You are a data analyst writing a brief, plain-English summary of \
an exploratory data analysis. You are given ONLY pre-computed numbers (dataset \
size, correlations, distributions, skewness, outliers, category counts).

Rules:
- Use ONLY the numbers provided. NEVER invent, estimate, or compute a new \
statistic. If a number is not given, do not state it.
- Write 3-6 short paragraphs (or tight bullet groups) covering: overall shape of \
the data, the most notable correlations (name the columns and the r value), any \
strong skew or outliers worth knowing, and stand-out categorical patterns.
- Be concrete and reference actual column names and values. Avoid hedging filler.
- Plain prose for a non-technical stakeholder. No code, no markdown headers."""


def _compact_eda(eda: EDAResult) -> dict:
    """Trim the EDA down to the fields worth narrating (keeps the prompt small)."""
    return {
        "n_rows": eda.n_rows,
        "n_cols": eda.n_cols,
        "numeric_cols": eda.numeric_cols,
        "categorical_cols": eda.categorical_cols,
        "datetime_cols": eda.datetime_cols,
        "top_correlations": eda.top_correlations,
        "skewness": eda.skewness,
        "outlier_summary": eda.outlier_summary,
        "categorical_distributions": eda.categorical_distributions,
        "describe": eda.describe,
    }


def narrate(eda: EDAResult) -> str:
    payload = _compact_eda(eda)
    user = (
        "Here are the computed EDA results. Write the summary using only these "
        "numbers.\n\n" + json.dumps(payload, indent=2, default=str)
    )
    try:
        text = base.call_text(config.INSIGHTS_MODEL, SYSTEM_PROMPT + base.PRECISION_RULE, user)
    except Exception as exc:  # noqa: BLE001
        return (
            "*(The narrative could not be generated by the local model: "
            f"{exc}. The computed statistics and charts above are unaffected.)*"
        )
    return text or "*(The model returned an empty narrative.)*"


TAKEAWAYS_PROMPT = """You are a data analyst. You are given a list of factual, \
pre-computed findings about a cleaned dataset (data-quality notes, distribution \
shapes, correlations, category balance). Turn them into 3-5 short, actionable \
takeaways for a stakeholder deciding what to do next with this data.

Rules:
- Base every takeaway ONLY on the findings given. Do not invent numbers or facts.
- Each takeaway is ONE sentence, plain English, and where useful suggests an action \
(e.g. "treat income with a log transform before modelling", "verify the outliers in X").
- Output ONE takeaway per line, each starting with "- ". No headers, no preamble."""


def key_takeaways(findings_for_llm: list[dict]) -> list[str]:
    """Return a short list of actionable takeaway strings grounded in the findings."""
    if not findings_for_llm:
        return []
    user = (
        "Findings:\n" + json.dumps(findings_for_llm, indent=2, default=str)
        + "\n\nWrite the takeaways now."
    )
    try:
        text = base.call_text(config.INSIGHTS_MODEL, TAKEAWAYS_PROMPT + base.PRECISION_RULE, user)
    except Exception:  # noqa: BLE001
        return []
    items = []
    for line in text.splitlines():
        line = line.strip().lstrip("-•*0123456789. ").strip()
        if line:
            items.append(line)
    return items[:5]
